source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '7.1'
inhibit_all_warnings!

pod 'RestKit', '0.23.1'
pod 'Parse-iOS-SDK', '1.2.19'
pod 'IOSLinkedInAPI', '1.0'
pod 'TTTAttributedLabel'
pod 'GCPlaceholderTextView', '1.0.1'
pod 'CSStickyHeaderFlowLayout', '0.2.3'
pod 'SWTableViewCell'
pod 'ReactiveCocoa'
pod 'BlocksKit'
pod 'GoogleAnalytics-iOS-SDK', '3.0.9'
pod 'apptentive-ios'
pod 'BSImagePicker', '~> 0.7'
pod 'AviarySDK', '4.3.3'
pod 'DSXActivityIndicator', '0.0.1'
pod 'MBProgressHUD'
pod 'Intercom'
pod 'AMSmoothAlert'
pod 'UzysCircularProgressPullToRefresh'
pod 'FontAwesomeKit'
pod 'IBActionSheet'
pod 'NSAttributedString+CCLFormat'
